const fs = require('fs');
const path = require('path');

const COURSES_JSON_PATH = path.join(__dirname, '../data/courses.json');
const COURSES_DIR = path.join(__dirname, '../data/courses');

// Regex to extract YAML-like frontmatter
const frontmatterRegex = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/;

function parseFrontmatter(fileContent, filePath) {
    const match = fileContent.match(frontmatterRegex);
    if (!match) {
        throw new Error(`Missing or invalid frontmatter in ${filePath}`);
    }

    const fmText = match[1];
    const metadata = {};

    // Simple key-value parser for basic frontmatter
    const lines = fmText.split('\n');
    for (let line of lines) {
        line = line.trim();
        if (!line || line.startsWith('#')) continue;
        
        const colonIdx = line.indexOf(':');
        if (colonIdx === -1) continue;

        const key = line.substring(0, colonIdx).trim();
        let value = line.substring(colonIdx + 1).trim();

        // Strip quotes if present
        if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
            value = value.substring(1, value.length - 1);
        }

        metadata[key] = value;
    }

    // Convert order to number
    if (metadata.order !== undefined) {
        metadata.order = parseInt(metadata.order, 10);
    }

    return metadata;
}

function buildCourses() {
    console.log('Starting course build process...');

    if (!fs.existsSync(COURSES_JSON_PATH)) {
        console.error('Error: courses.json not found!');
        process.exit(1);
    }

    const coursesData = JSON.parse(fs.readFileSync(COURSES_JSON_PATH, 'utf8'));

    coursesData.forEach(course => {
        console.log(`Processing course: ${course.id}...`);
        const courseDir = path.join(COURSES_DIR, course.id);

        if (!fs.existsSync(courseDir)) {
            console.warn(`Warning: Directory for course '${course.id}' does not exist. Skipping.`);
            return;
        }

        const files = fs.readdirSync(courseDir).filter(f => f.endsWith('.md'));
        const lessons = [];

        files.forEach(file => {
            const filePath = path.join(courseDir, file);
            const content = fs.readFileSync(filePath, 'utf8');

            try {
                const metadata = parseFrontmatter(content, filePath);

                // Validation
                const requiredFields = ['title', 'module_id', 'module_title', 'order'];
                const missing = requiredFields.filter(f => metadata[f] === undefined);
                if (missing.length > 0) {
                    throw new Error(`Missing required fields: ${missing.join(', ')}`);
                }

                lessons.push({
                    id: file.replace('.md', ''),
                    file: file,
                    title: metadata.title,
                    module_id: metadata.module_id,
                    module_title: metadata.module_title,
                    order: metadata.order
                });

            } catch (err) {
                console.error(`Validation Error in ${file}: ${err.message}`);
                process.exit(1);
            }
        });

        // Group into modules
        const modulesMap = new Map();

        lessons.forEach(lesson => {
            if (!modulesMap.has(lesson.module_id)) {
                modulesMap.set(lesson.module_id, {
                    id: lesson.module_id,
                    title: lesson.module_title,
                    lessons: []
                });
            }
            
            const mod = modulesMap.get(lesson.module_id);
            
            // Check for duplicate order
            if (mod.lessons.some(l => l.order === lesson.order)) {
                console.error(`Validation Error: Duplicate order '${lesson.order}' found in module '${lesson.module_id}' for course '${course.id}'.`);
                process.exit(1);
            }

            mod.lessons.push(lesson);
        });

        // Sort lessons inside modules
        const modulesArray = Array.from(modulesMap.values());
        modulesArray.forEach(mod => {
            mod.lessons.sort((a, b) => a.order - b.order);
            // Remove the 'order', 'module_id', 'module_title' properties as they are not needed in final JSON
            mod.lessons = mod.lessons.map(l => ({
                id: l.id,
                title: l.title,
                file: l.file
            }));
        });

        // Generate final index.json structure
        const indexJson = {
            id: course.id,
            title: course.title,
            description: course.description,
            category: course.category,
            _comment: "DO NOT EDIT THIS FILE MANUALLY. It is auto-generated by scripts/build.js based on Markdown frontmatter.",
            modules: modulesArray
        };

        const indexJsonPath = path.join(courseDir, 'index.json');
        fs.writeFileSync(indexJsonPath, JSON.stringify(indexJson, null, 2));
        console.log(`Successfully generated index.json for '${course.id}' (${lessons.length} lessons mapped to ${modulesArray.length} modules).`);
    });

    console.log('Build completed successfully!');
}

buildCourses();
